# Scripts that creates the whole project's folder structure.
# It is representative to where (the folders) code files are stored 
# and keeps the same structure.

cmake_minimum_required (VERSION ${CMAKE_MIN_VERSION})

source_group("CMake" REGULAR_EXPRESSION "CMake/+\\w*")
source_group("Engine" REGULAR_EXPRESSION "Engine/+\\w*")
	source_group("Engine\\Graphics" REGULAR_EXPRESSION "Engine/+Graphics/+\\w*")
	source_group("Engine\\Multiplatform\\Core\\Debug" REGULAR_EXPRESSION "Engine/+Multiplatform/+Core/+Debug/+\\w*")
	source_group("Engine\\Multiplatform\\Core\\File" REGULAR_EXPRESSION "Engine/+Multiplatform/+Core/+File/+\\w*")
	source_group("Engine\\Multiplatform\\Core\\Graphics" REGULAR_EXPRESSION "Engine/+Multiplatform/+Core/+Graphics/+\\w*")
	source_group("Engine\\Multiplatform\\Core\\Input" REGULAR_EXPRESSION "Engine/+Multiplatform/+Core/+Input/+\\w*")
	source_group("Engine\\Multiplatform\\Core\\Maintenance" REGULAR_EXPRESSION "Engine/+Multiplatform/+Core/+Maintenance/+\\w*")
	source_group("Engine\\Multiplatform\\Core\\Math" REGULAR_EXPRESSION "Engine/+Multiplatform/+Core/+Math/+\\w*")
		source_group("Engine\\Multiplatform\\Core\\Math\\Geometry" REGULAR_EXPRESSION "Engine/+Multiplatform/+Core/+Math/+Geometry/+\\w*")
		source_group("Engine\\Multiplatform\\Core\\Math\\Vectors" REGULAR_EXPRESSION "Engine/+Multiplatform/+Core/+Math/+Vectors/+\\w*")
	source_group("Engine\\Multiplatform\\Core\\Physics" REGULAR_EXPRESSION "Engine/+Multiplatform/+Core/+Physics/+\\w*")
		source_group("Engine\\Multiplatform\\Core\\Physics\\Mechanics" REGULAR_EXPRESSION "Engine/+Multiplatform/+Core/+Physics/+Mechanics/+\\w*")
	source_group("Engine\\Multiplatform\\Core\\Profiling" REGULAR_EXPRESSION "Engine/+Multiplatform/+Core/+Profiling/+\\w*")
	source_group("Engine\\Multiplatform\\Core\\Shaders" REGULAR_EXPRESSION "Engine/+Multiplatform/+Core/+Shaders/+\\w*")
		source_group("Engine\\Multiplatform\\Core\\Shaders\\Fragment" REGULAR_EXPRESSION "Engine/+Multiplatform/+Core/+Shaders/+Fragment/+\\w*")
		source_group("Engine\\Multiplatform\\Core\\Shaders\\Vertex" REGULAR_EXPRESSION "Engine/+Multiplatform/+Core/+Shaders/+Vertex/+\\w*")
	source_group("Engine\\Multiplatform\\Core\\StdInterface" REGULAR_EXPRESSION "Engine/+Multiplatform/+Core/+StdInterface/+\\w*")
	source_group("Engine\\Multiplatform\\Core\\System" REGULAR_EXPRESSION "Engine/+Multiplatform/+Core/+System/+\\w*")
		source_group("Engine\\Multiplatform\\Core\\System\\Hashing" REGULAR_EXPRESSION "Engine/+Multiplatform/+Core/+System/+Hashing/+\\w*")
		source_group("Engine\\Multiplatform\\Core\\System\\Type" REGULAR_EXPRESSION "Engine/+Multiplatform/+Core/+System/+Type/+\\w*")
	source_group("Engine\\Multiplatform\\HighLevel\\Application" REGULAR_EXPRESSION "Engine/+Multiplatform/+HighLevel/+Application/+\\w*")
		source_group("Engine\\Multiplatform\\HighLevel\\Application\\Controller" REGULAR_EXPRESSION "Engine/+Multiplatform/+HighLevel/+Application/+Controller/+\\w*")
	source_group("Engine\\Multiplatform\\HighLevel\\Camera" REGULAR_EXPRESSION "Engine/+Multiplatform/+HighLevel/+Camera/+\\w*")
		source_group("Engine\\Multiplatform\\HighLevel\\Camera\\Controller" REGULAR_EXPRESSION "Engine/+Multiplatform/+HighLevel/+Camera/+Controller/+\\w*")
	source_group("Engine\\Multiplatform\\HighLevel\\Graphics" REGULAR_EXPRESSION "Engine/+Multiplatform/+HighLevel/+Graphics/+\\w*")
		source_group("Engine\\Multiplatform\\HighLevel\\Graphics\\Factories" REGULAR_EXPRESSION "Engine/+Multiplatform/+HighLevel/+Graphics/+Factories/+\\w*")
		source_group("Engine\\Multiplatform\\HighLevel\\Graphics\\Spawners" REGULAR_EXPRESSION "Engine/+Multiplatform/+HighLevel/+Graphics/+Spawners/+\\w*")

# Add platform-specific files
if (${CMAKE_SYSTEM_NAME} STREQUAL  "Windows")
	include("CMake/BuildWindowsProjectTree.cmake")
else()
	message(FATAL_ERROR "Your system is not supported. Your system is evaluated to be ${CMAKE_SYSTEM_NAME}.")
endif()
